// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWsk1rFSrWc0viRzKrnMV1AqhOTt-H_PQ',
    appId: '1:819604090588:web:ee5df4388c4f55c4350e19',
    messagingSenderId: '819604090588',
    projectId: 'flutterapp-5b028',
    authDomain: 'flutterapp-5b028.firebaseapp.com',
    storageBucket: 'flutterapp-5b028.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB4oGxlqWel2Zx1Yapyp-gtgQ8qqLoUZo',
    appId: '1:819604090588:android:2d724d8fae01c9d3350e19',
    messagingSenderId: '819604090588',
    projectId: 'flutterapp-5b028',
    storageBucket: 'flutterapp-5b028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3hG6CLolE_HCaNptLEyMV0jgTUTjzYEk',
    appId: '1:819604090588:ios:268172d99dbc66bf350e19',
    messagingSenderId: '819604090588',
    projectId: 'flutterapp-5b028',
    storageBucket: 'flutterapp-5b028.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3hG6CLolE_HCaNptLEyMV0jgTUTjzYEk',
    appId: '1:819604090588:ios:83e10129089adb59350e19',
    messagingSenderId: '819604090588',
    projectId: 'flutterapp-5b028',
    storageBucket: 'flutterapp-5b028.appspot.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
